package com.example.themoviebookingapp.utils

const val BASE_URL ="https://tmba.padc.com.mm"
const val MOVIE_BASE_URL ="https://api.themoviedb.org"
const val IMAGE_BASE_URL = "https://image.tmdb.org/t/p/w400/"
const val CAST_IMAGE_BASE_URL = "https://image.tmdb.org/t/p/original/"


const val API_SIGNIN_WITH_EMAIL ="/api/v1/register"
const val API_LOGIN_WITH_EMAIL ="/api/v1/email-login"
const val API_PROFILE="/api/v1/profile"
const val API_GET_NOW_PLAYING = "/3/movie/now_playing"
const val API_GET_GENRES = "/3/genre/movie/list"
const val API_UPCOMING="/3/movie/upcoming"
const val API_GET_MOVIE_DETAILS = "/3/movie"
const val API_GET_CREDITS_BY_MOVIE = "/3/movie"
const val API_GET_CINEMA_DAY_TIMESLOT ="/api/v1/cinema-day-timeslots"
const val API_GET_SEATING_PLAN ="/api/v1/seat-plan"
const val  API_GET_SNACK = "/api/v1/snacks"
const val API_GET_PAYMENT_METHOD = "/api/v1/payment-methods"
const val API_CREATE_NEW_CARD = "/api/v1/card"
const val API_CHECK_OUT ="/api/v1/checkout"

//params
const val MOVIE_API_KEY="9fc43e3d43557a704ac035a2f15f6102"
const val PARAM_API_KEY = "api_key"
const val PARAM_PAGE = "page"
const val NAME = "name"
const val EMAIL = "email"
const val PHONE = "phone"
const val PASSWORD = "password"
const val AUTHORIZATION = "Authorization"
const val MOVIE_ID="movie_id"
const val DATE ="date"
const val CINEMA_DAY_TIMESLOT_ID = "cinema_day_timeslot_id"
const val BOOKING_DATE = "booking_date"
const val CARD_NUMBER = "card_number"
const val CARD_HOLDER = "card_holder"
const val EXPIRATION_DATE ="expiration_date"
const val CVC ="cvc"
